---
title: "Descriptive statistics"
author: "Carolien C.H.M. Maas"
date: "November 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Describe data

### Load packages, functions, and data 
```{r, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
# erase memory
rm(list = ls(all.names = TRUE))

# for reproducibility
set.seed(100)

# load libraries
library(mice)
library(survival)
library(survminer)
library(stats)
library(prodlim)
library(utils)
source("Z:/Project Melanoom/PaperMelanoma/Code/PaperMelanomaFunctions.R")
```

```{r, eval=TRUE}
prepare.data <- function(type){
  # Load imputed data set 
  load(paste0("Z:/Project Melanoom/PaperMelanoma/Data/", type, "/", type, ".data.RData"))
  imputed.data <- eval(parse(text=paste0("imputed.", type, ".data")))
  last.imputed.data.set <- mice::complete(imputed.data, m)
  
  assign(paste0("S.Rec.", type), survival::Surv(exp(last.imputed.data.set$logRec.composite.time), 
                                                last.imputed.data.set$Rec.composite))
  assign(paste0("S.MSM.", type), survival::Surv(exp(last.imputed.data.set$logFU.time), 
                                                last.imputed.data.set$MSM=="Death by melanoma"))
  
  assign(paste0("imputed.", type, ".data"), imputed.data)
  assign(paste0("last.imputed.", type, ".data.set"), last.imputed.data.set)
  
  save(list=c(paste0("dd.", type), "m",
              paste0(type, ".data.to.be.imputed"),
              paste0("imputed.", type, ".data"),
              paste0("last.imputed.", type, ".data.set"),
              paste0("S.Rec.", type),
              paste0("S.MSM.", type)),
       file=paste0("Z:/Project Melanoom/PaperMelanoma/Data/", type, "/", type, ".data.Rdata"), compress=TRUE)
}
prepare.data(type="training")
prepare.data(type="validation")
```
# Median time to recurrence and follow-up time
```{r, eval=TRUE}
median.time <- function(data=NA, type=NA){
  # time in total
  if (type=="Rec"){
    median.time.total <- stats::quantile(prodlim::prodlim(prodlim::Hist(exp(logRec.composite.time), 
                                                                        Rec.composite)~1, data=data[data$Center!="Australia",], reverse=TRUE))
    median.time <- stats::quantile(prodlim::prodlim(prodlim::Hist(exp(logRec.composite.time), 
                                                                  Rec.composite)~Center, data=data, reverse=TRUE))
  } else if (type=="FU"){
    median.time.total <- stats::quantile(prodlim::prodlim(prodlim::Hist(exp(logFU.time), 
                                                                        MSM=="Death by melanoma")~1, 
                                                          data=data[data$Center!="Australia",], 
                                                          reverse=TRUE))
    median.time <- stats::quantile(prodlim::prodlim(prodlim::Hist(exp(logFU.time), 
                                                                  MSM=="Death by melanoma")~Center, 
                                                    data=data, 
                                                    reverse=TRUE))
  }
  # save in tab.time
  tab.time <- c("Total Development", paste(sprintf("%.1f", median.time.total$quantile[3]),
                   paste0("[", sprintf("%.1f", median.time.total$quantile[4]), "; ",
                          sprintf("%.1f", median.time.total$quantile[2]), "]")))
  
  # time per center
  for (center in c("Amsterdam", "Berlin", "Rotterdam", "Warsaw", "Australia")){
    sel.center <- eval(parse(text=paste0("median.time$Center==\"", center, "\"")))
    q.center <- median.time$quantile[sel.center]
    med <- q.center[3]
    lower <- q.center[4]
    upper <- q.center[2]
    tab.time <- rbind(tab.time, c(center, paste(sprintf("%.1f", med), paste0("[", sprintf("%.1f", lower), "; ", sprintf("%.1f", upper), "]"))))
  }
  
  return(tab.time)
}
load(paste0("Z:/Project Melanoom/PaperMelanoma/Data/training/training.data.RData"))
load(paste0("Z:/Project Melanoom/PaperMelanoma/Data/validation/validation.data.RData"))
med.Rec <- median.time(data=rbind(training.data.to.be.imputed[, c("logRec.composite.time", "Rec.composite", "Center")], 
                       validation.data.to.be.imputed[, c("logRec.composite.time", "Rec.composite", "Center")]), type="Rec")
med.FU <- median.time(data=rbind(training.data.to.be.imputed[, c("logFU.time", "MSM", "Center")], 
                       validation.data.to.be.imputed[, c("logFU.time", "MSM", "Center")]), type="FU")
# save to .txt
write.table(cbind(c("Recurrence time", "Follow-up time"), 
                  rbind(c(med.Rec[, -1]), c(med.FU[,-1]))),
              file=paste0("Z:/Project Melanoom/PaperMelanoma/Results/med.table.txt"),
              row.names=FALSE, sep=",")
```

# Kaplan-Meier estimates of recurrence and MSM at 5 years
```{r, eval=TRUE}
est.CI.n <- function(KM=NULL, horizon=5){
  t <- max(KM$time[KM$time<=horizon])
  est <- 100*KM$surv[KM$time==t]
  est.LCI <- 100*KM$lower[KM$time==t]
  est.UCI <- 100*KM$upper[KM$time==t]
  n <- sum(KM$n.event[KM$time<=horizon])
  return(list(t=t, est=est, est.LCI=est.LCI, est.UCI=est.UCI, n=n))
}

Rec.MSM.table <- function(horizon=5, type=NULL, data.to.be.imputed=NULL){
  # select last imputed data set
  imputed.data <- eval(parse(text=paste0("imputed.", type, ".data")))
  last.imputed.data.set <- mice::complete(imputed.data, m)
  
  # all patients, Recurrence
  S.Rec <- eval(parse(text=paste0("S.Rec.", type)))
  KM.Rec.all <- survival::survfit(S.Rec~1, data=data.to.be.imputed)
  out.Rec.all <- est.CI.n(KM=KM.Rec.all, horizon=horizon)
  
  # only negative patients, Recurrence
  KM.Rec.neg <-survival::survfit(S.Rec[data.to.be.imputed$SNstatus=="Negative"]~1, data=data.to.be.imputed)
  out.Rec.neg <- est.CI.n(KM=KM.Rec.neg, horizon=horizon)
  
  # only positive patients, Recurrence
  KM.Rec.pos <- survival::survfit(S.Rec[data.to.be.imputed$SNstatus=="Positive"]~1, data=data.to.be.imputed)
  out.Rec.pos <- est.CI.n(KM=KM.Rec.pos, horizon=horizon)
  
  # all patients, MSM
  S.MSM <- eval(parse(text=paste0("S.MSM.", type)))
  KM.MSM.all <- survival::survfit(S.MSM~1, data=data.to.be.imputed)
  out.MSM.all <- est.CI.n(KM=KM.MSM.all, horizon=horizon)
  
  # negative patients, MSM
  KM.MSM.neg <- survival::survfit(S.MSM[data.to.be.imputed$SNstatus=="Negative"]~1, data=data.to.be.imputed)
  out.MSM.neg <- est.CI.n(KM=KM.MSM.neg, horizon=horizon)
  
  # positive patients, MSM
  KM.MSM.pos <- survival::survfit(S.MSM[data.to.be.imputed$SNstatus=="Positive"]~1, data=data.to.be.imputed)
  out.MSM.pos <- est.CI.n(KM=KM.MSM.pos, horizon=horizon)
  
  # merge in one table
  Rec.MSM.table <- data.frame(n=c(nrow(data.to.be.imputed),
                                  sum(data.to.be.imputed$SNstatus=="Negative"),
                                  sum(data.to.be.imputed$SNstatus=="Positive")),
                              e1=rep("", 3),
                              n.Rec=c(out.Rec.all$n, 
                                      out.Rec.neg$n, 
                                      out.Rec.pos$n),
                              n.MSM=c(out.MSM.all$n, 
                                      out.MSM.neg$n, 
                                      out.MSM.pos$n),
                              e2=rep("", 3),
                              Rec=sprintf("%.1f", c(out.Rec.all$est,
                                                    out.Rec.neg$est,
                                                    out.Rec.pos$est)),
                              Rec.LCI=sprintf("%.1f", c(out.Rec.all$est.LCI,
                                                        out.Rec.neg$est.LCI,
                                                        out.Rec.pos$est.LCI)),
                              Rec.UCI=sprintf("%.1f", c(out.Rec.all$est.UCI,
                                                        out.Rec.neg$est.UCI,
                                                        out.Rec.pos$est.UCI)),
                              e3=rep("", 3),
                              MSM=sprintf("%.1f", c(out.MSM.all$est,
                                                    out.MSM.neg$est,
                                                    out.MSM.pos$est)),
                              MSM.LCI=sprintf("%.1f", c(out.MSM.all$est.LCI,
                                                        out.MSM.neg$est.LCI,
                                                        out.MSM.pos$est.LCI)),
                              MSM.UCI=sprintf("%.1f", c(out.MSM.all$est.UCI, 
                                                        out.MSM.neg$est.UCI, 
                                                        out.MSM.pos$est.UCI)))
  row.names(Rec.MSM.table) <- c("All", "Negative", "Positive")
  
  return(Rec.MSM.table)
}
horizon <- 5
train.table <- Rec.MSM.table(horizon=horizon, type="training", 
                             data.to.be.imputed=training.data.to.be.imputed)
val.table <- Rec.MSM.table(horizon=horizon, type="validation", 
                           data.to.be.imputed=validation.data.to.be.imputed)

utils::write.table(cbind(train.table, rep("", 3), val.table),
                   file=paste0("Z:/Project Melanoom/PaperMelanoma/Results/Rec.MSM.table.txt"),
                   row.names=TRUE, sep=",")
```

# Restrict survival at 5 years
```{r, eval=TRUE}
for (type in c("training",  "validation")){
  load(paste0("Z:/Project Melanoom/PaperMelanoma/Data/", type, "/", type, ".data.Rdata"))
  for (outcome in c("Rec", "MSM")){
    S <- eval(parse(text=paste0("S.", outcome, ".", type)))
    cat("Number of patients with follow-up for", outcome, "after 5 years:", sum(S[, 1]>5), "in", type, " data \n")
    S.5 <- S
    S.5[S[,1]>5, 1] <- 5 # set time to 5
    S.5[S[,1]>5, 2] <- 0 # set censoring
    
    assign(paste0("S.", outcome, ".5.", type), S.5)
  }
  save(list=c(paste0("dd.", type), "m", "horizon",
              paste0(type, ".data.to.be.imputed"),
              paste0("imputed.", type, ".data"),
              paste0("last.imputed.", type, ".data.set"),
              paste0("S.Rec.", type),
              paste0("S.MSM.", type),
              paste0("S.Rec.5.", type),
              paste0("S.MSM.5.", type)),
     file=paste0("Z:/Project Melanoom/PaperMelanoma/Data/", type, "/", type, ".data.Rdata"), compress=TRUE)
}
```
### Kaplan-Meier plots
```{r, eval=TRUE}
pooled.data <- rbind(last.imputed.training.data.set, last.imputed.validation.data.set)
S.Rec.pooled <- survival::Surv(exp(pooled.data$logRec.composite.time),
                               pooled.data$Rec.composite)
S.Rec.5.pooled <- S.Rec.pooled
S.Rec.5.pooled[S.Rec.pooled[,1]>5, 1] <- 5 # set time to 5
S.Rec.5.pooled[S.Rec.pooled[,1]>5, 2] <- 0 # set censoring

png(file=paste0("Z:/Project Melanoom/PaperMelanoma/Results/KM.Rec.composite.png"), width=16, height=16, units="cm", res=300)
survminer::ggsurvplot(survival::survfit(S.Rec.5.pooled ~ Center, 
                                        data=pooled.data), 
                      legend.title="",
                      legend.labs=c("Rotterdam", "Berlin", "Warsaw", "Amsterdam", "Australia"),
                      title="Recurrence-free survival",
                      ylab="Recurrence-free survival probability",
                      xlab="Time in years",
                      conf.int=TRUE, risk.table=TRUE)+
  ggplot2::guides(colour=guide_legend(nrow=2))
grDevices::dev.off()
png(file=paste0("Z:/Project Melanoom/PaperMelanoma/Results/KM.Rec.composite.zoomed.png"), width=16, height=16, units="cm", res=300)
survminer::ggsurvplot(survival::survfit(S.Rec.5.pooled ~ Center, 
                                        data=pooled.data), 
                      legend.title="",
                      legend.labs=c("Rotterdam", "Berlin", "Warsaw", "Amsterdam", "Australia"),
                      title="Recurrence-free survival",
                      ylab="Recurrence-free survival probability",
                      xlab="Time in years",
                      ylim=c(0.6, 1),
                      conf.int=TRUE, risk.table=TRUE)+
  ggplot2::guides(colour=guide_legend(nrow=2))
grDevices::dev.off()

S.MSM.pooled <- survival::Surv(exp(pooled.data$logFU.time),
                               pooled.data$MSM=="Death by melanoma")
S.MSM.5.pooled <- S.MSM.pooled
S.MSM.5.pooled[S.MSM.pooled[,1]>5, 1] <- 5 # set time to 5
S.MSM.5.pooled[S.MSM.pooled[,1]>5, 2] <- 0 # set censoring

png(file=paste0("Z:/Project Melanoom/PaperMelanoma/Results/KM.MSM.png"), width=16, height=16, units="cm", res=300)
survminer::ggsurvplot(survival::survfit(S.MSM.5.pooled ~ Center, 
                                        data=pooled.data), 
                      legend.title="",
                      legend.labs=c("Rotterdam", "Berlin", "Warsaw", "Amsterdam", "Australia"),
                      title="Melanoma-specific survival",
                      ylab="Melanoma-specific survival probability",
                      xlab="Time in years",
                      conf.int=TRUE, risk.table=TRUE)+
  ggplot2::guides(colour=guide_legend(nrow=2))
grDevices::dev.off()
png(file=paste0("Z:/Project Melanoom/PaperMelanoma/Results/KM.MSM.zoomed.png"), width=16, height=16, units="cm", res=300)
survminer::ggsurvplot(survival::survfit(S.MSM.5.pooled ~ Center, 
                                        data=pooled.data), 
                      legend.title="",
                      legend.labs=c("Rotterdam", "Berlin", "Warsaw", "Amsterdam", "Australia"),
                      title="Melanoma-specific survival",
                      ylab="Melanoma-specific survival probability",
                      xlab="Time in years",
                      ylim=c(0.6, 1),
                      conf.int=TRUE, risk.table=TRUE)+
  ggplot2::guides(colour=guide_legend(nrow=2))
grDevices::dev.off()
```
