---
title: "Create histogram with risk scores"
author: "Carolien C.H.M. Maas"
date: "14-11-2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Create calibration plots

### Load packages, functions, and data 
```{r, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
# erase memory
rm(list = ls(all.names = TRUE))

# for reproducibility
set.seed(100)

# load libraries
library(grDevices)
library(stats)
library(survival)
source("Z:/Project Melanoom/PaperMelanoma/Code/PaperMelanomaFunctions.R")
```

# Risk score distribution
```{r, eval=TRUE}
load('Z:/Project Melanoom/PaperMelanoma/Data/training/training.data.RData')
# baseline hazard of MSM
f.MSM.basehaz <- survival::basehaz(f.mi.BS.MSM.5,TRUE)
h0.MSM <- f.MSM.basehaz$hazard[f.MSM.basehaz$time==max(f.MSM.basehaz$time[f.MSM.basehaz$time<=horizon])]
lp.MSM <- f.mi.BS.MSM.5$linear

# lp range MSM
rc.MSM <- f.mi.BS.MSM.5$coef[1]*rc.Rec
int.MSM <- f.mi.BS.MSM.5$coef[1]*int.Rec
max.range <- 16
points.range <- 0:max.range
lp.points.Rec.5 <- int.Rec+rc.Rec*points.range
lp.points.MSM.5 <- int.MSM+rc.MSM*points.range

# Recurrence lp scores
Breslow.trunc <- last.imputed.training.data.set$Breslow
Breslow.trunc[last.imputed.training.data.set$Breslow<0.1] <- .1
Breslow.trunc[last.imputed.training.data.set$Breslow>7] <- 7
lp.score.Rec <- predict(f.mi.BS.Rec.5,newdata=data.frame(SNstatus=last.imputed.training.data.set$SNstatus,
                                                         Age.SN=last.imputed.training.data.set$Age.SN,
                                                         Ulceration=last.imputed.training.data.set$Ulceration,
                                                         Loc_CAT=last.imputed.training.data.set$Loc_CAT,
                                                         Breslow=Breslow.trunc,
                                                         Rdamcrit=last.imputed.training.data.set$Rdamcrit))
mean(lp.score.Rec)
score.Rec <- round((lp.score.Rec-int.Rec)/rc.Rec,0)
max.breaks <- max.range+1
h.Rec <- hist(score.Rec,plot=FALSE,breaks=0:max.breaks,right=FALSE)

# score table
data.frame(table(score.Rec)/length(score.Rec))
```

# Plot of risk score distribution
```{r, eval=TRUE, message=FALSE}
h.plot <- h.Rec
h.plot$density <- 100*h.Rec$density
p.Rec <- fun.event(lp=lp.points.Rec.5, h0=h0.Rec)
p.MSM <- fun.event(lp=lp.points.MSM.5, h0=h0.MSM)
x.lim <- c(0, max.range+1)
y.lim <- c(0, 100)
y.lim.hist <- c(0, 25)
png(file=paste0("Z:/Project Melanoom/PaperMelanoma/Results/Risk.distribution.png"))
par(mar = c(5,5,2,5))
plot(h.plot,freq=FALSE,axes=FALSE, xlab=NA, xlim=x.lim, ylab=NA,ylim=y.lim.hist,main=NA,col='white')
abline(h=(0:30)*1,col="light grey",lty=2)
axis(side = 4)
mtext(side = 4, line = 3, 'Risk score distribution (%)')
par(new = TRUE)
plot(h.plot,freq=FALSE,axes=FALSE, xlab=NA, xlim=x.lim, ylab=NA,ylim=y.lim.hist,main=NA,col="white")
par(new = TRUE)
plot(points.range,p.Rec*100,type="b",lwd=1,xlim=x.lim,ylim=y.lim,pch=15, xlab="Risk score",ylab="Predicted 5-year risk (%)")
points(points.range,p.MSM*100,type="b",lwd=1,xlim=x.lim,ylim=y.lim,pch=16)
legend(x=0,y=100,legend=c("Recurrence","Melanoma-specific mortality"),pch=c(15,16),cex=.9,bg='white')
grDevices::dev.off()
```

```{r, eval=TRUE, echo=FALSE}
par(mar = c(5,5,2,5))
plot(h.plot,freq=FALSE,axes=FALSE, xlab=NA, xlim=x.lim, ylab=NA,ylim=y.lim.hist,main=NA,col='white')
abline(h=(0:30)*1,col="light grey",lty=2)
axis(side = 4)
mtext(side = 4, line = 3, 'Risk score distribution (%)')
par(new = TRUE)
plot(h.plot,freq=FALSE,axes=FALSE, xlab=NA, xlim=x.lim, ylab=NA,ylim=y.lim.hist,main=NA,col="white")
par(new = TRUE)
plot(points.range,p.Rec*100,type="b",lwd=1,xlim=x.lim,ylim=y.lim,pch=15, xlab="Risk score",ylab="Predicted 5-year risk (%)")
points(points.range,p.MSM*100,type="b",lwd=1,xlim=x.lim,ylim=y.lim,pch=16)
legend(x=0,y=100,legend=c("Recurrence","Melanoma-specific mortality"),pch=c(15,16),cex=.9,bg='white')

# table of risk distribution
cbind(points.range, round(p.Rec*100, 1), round(p.MSM*100, 1))[c(1, 9, 10, 12, 13),]
```
# Save for Rshiny app
```{r, eval=TRUE}
coef.Rec <- stats::coef(f.mi.BS.Rec.5)
center.Rec <- f.mi.BS.Rec.5$center
save(h0.Rec, h0.MSM, coef.Rec, c.Breslow, center.Rec, MSM.cal.fact,
     file=paste0('Z:/Project Melanoom/PaperMelanoma/Results/h0.Rec.MSM.Rdata'), compress=TRUE)
save(list=c("dd.training", "training.data.to.be.imputed", "m", "imputed.training.data", "last.imputed.training.data.set", "horizon", "S.Rec.5.training", "S.MSM.5.training",
            "f.mi.full.Rec.5", "f.mi.BS.Rec.5", "f.mi.full.MSM.5.refit", "f.mi.BS.MSM.5.refit", "f.mi.BS.MSM.5", "MSM.cal.fact", "c.Breslow", 
            "form.full.Rec.5", "form.BS.Rec.5", "form.full.MSM.5.refit", "form.BS.MSM.5.refit", 
            "rc.Rec", "int.Rec", "h0.Rec", "h0.MSM", "coef.Rec", "center.Rec", "h.Rec", "lp.points.Rec.5", "lp.points.MSM.5", "lp.score.Rec", "lp.MSM", 
            "max.breaks", "h.plot", "y.lim.hist", "x.lim"),
     file='Z:/Project Melanoom/PaperMelanoma/Data/training/training.data.Rdata', compress=TRUE)
```
