---
output: word_document
---

```{r setup, include=FALSE}
# clear all
rm(list = ls(all.names = TRUE))
if(!is.null(dev.list())) dev.off()
cat("\014")

# load packages
library(arsenal)
library(knitr)

load("Z:/Project Melanoom/PaperMelanoma/Data/training/training.data.Rdata")
load("Z:/Project Melanoom/PaperMelanoma/Data/validation/validation.data.Rdata")
validation.data.to.be.imputed$Mitosis <- validation.data.to.be.imputed$Mitosis>0
validation.data.to.be.imputed$Mitosis <- factor(validation.data.to.be.imputed$Mitosis, labels=c("No", "Yes"))
pooled.data.to.be.imputed <- rbind(training.data.to.be.imputed, validation.data.to.be.imputed)
pooled.data.to.be.imputed$Continent <- c(rep("Europe", nrow(training.data.to.be.imputed)), 
                                         rep("Australie", nrow(validation.data.to.be.imputed)))

descr.table <- arsenal::tableby(Continent ~ SNstatus
                                +Sex
                                +Age.SN
                                +arsenal::includeNA(Ulceration)
                                +arsenal::includeNA(Loc_CAT)
                                +arsenal::includeNA(Histology)
                                +Breslow
                                +multiple.fields
                                +arsenal::includeNA(Mitosis)
                                +Recurrence
                                +dead
                                +MSM
                                +logRec.time
                                +logFU.time, 
                                data=pooled.data.to.be.imputed,
                                total.pos="before",
                                digits = 1,
                                test = F,
                                total = F,
                                numeric.test = "kwt", cat.test = "chisq",
                                numeric.stats = c("meansd", "medianq1q3", "range", "Nmiss2"),
                                cat.stats = c("countpct"),
                                stats.labels = list(
                                  meansd = "Mean (SD)",
                                  medianq1q3 = "Median (Q1, Q3)",
                                  range = "Min - Max",
                                  Nmiss2 = "Missing"
                                ))

descr.table.pos <- arsenal::tableby(Continent ~ Tot_SNs_pos
                                +Rdamcrit
                                +arsenal::includeNA(Dewar),
                                data=pooled.data.to.be.imputed[pooled.data.to.be.imputed$SNstatus=="Positive",],
                                total.pos="before",
                                digits = 1,
                                test = F,
                                total = T,
                                numeric.test = "kwt", cat.test = "chisq",
                                numeric.stats = c("meansd", "medianq1q3", "range", "Nmiss2"),
                                cat.stats = c("countpct"),
                                stats.labels = list(
                                  meansd = "Mean (SD)",
                                  medianq1q3 = "Median (Q1, Q3)",
                                  range = "Min - Max",
                                  Nmiss2 = "Missing"
                                ))

descr.table.neg <- arsenal::tableby(Continent ~ Tot_SNs_neg,
                                data=pooled.data.to.be.imputed[pooled.data.to.be.imputed$SNstatus=="Negative",],
                                total.pos="before",
                                digits = 1,
                                test = F,
                                total = T,
                                numeric.test = "kwt", cat.test = "chisq",
                                numeric.stats = c("meansd", "medianq1q3", "range", "Nmiss2"),
                                cat.stats = c("countpct"),
                                stats.labels = list(
                                  meansd = "Mean (SD)",
                                  medianq1q3 = "Median (Q1, Q3)",
                                  range = "Min - Max",
                                  Nmiss2 = "Missing"
                                ))
my_labels <- list(
  SNstatus = "SN status",
  Age.SN = "Age",
  Loc_CAT = "Location",
  multiple.fields = "Multiple fields",
  Tot_SNs_neg = "Total number of negative SN",
  Tot_SNs_pos = "Total number of positive SN",
  Rdamcrit = "SN tumour burden",
  Dewar = "Location metastasis in lymph",
  dead = "Deaths",
  MSM = "Melanoma specific mortality"
)
```

Table 1. Descriptive statistics.
```{r echo=FALSE}
knitr::kable(summary(descr.table, labelTranslations=my_labels))

# only negative
knitr::kable(summary(descr.table.neg, labelTranslations=my_labels))

# only positive
knitr::kable(summary(descr.table.pos, labelTranslations=my_labels))
```
