---
title: "Impute missing values of training and validation data using multiple imputation"
author: "Carolien C.H.M. Maas"
date: "January 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Multiple imputation

### Load packages, functions, and data 
```{r, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
# erase memory
rm(list = ls(all.names = TRUE))

# for reproducibility
set.seed(100)

# load libraries
library(mice)
```

Function to perform multiple imputation for training or validation data
```{r, eval=TRUE}
impute.missing.values <- function(type=NULL, m=1, new.imputation=FALSE){
  # load data
  if (type=="pooled"){
    load(paste0("Z:/Project Melanoom/PaperMelanoma/Data/training/training.data.Rdata"))
    load(paste0("Z:/Project Melanoom/PaperMelanoma/Data/validation/validation.data.Rdata"))
    pooled.data.to.be.imputed <- rbind(training.data.to.be.imputed, validation.data.to.be.imputed)
    dd.pooled<-rms::datadist(pooled.data.to.be.imputed)
  } else{
    load(paste0("Z:/Project Melanoom/PaperMelanoma/Data/", type, "/", type, ".data.Rdata"))
  }
  
  if (new.imputation){
    # impute data
    data.to.be.imputed <- eval(parse(text=paste0(type, ".data.to.be.imputed")))
    imputed.data <- mice::mice(data.to.be.imputed, m=m, maxit=5, print=FALSE, seed=500)
    # print(imputed.data$method)
    # print(imputed.data$loggedEvents)
    assign(paste0("imputed.", type, ".data"), imputed.data)
    save(list=c(paste0("imputed.", type, ".data")),
         file=paste0("Z:/Project Melanoom/PaperMelanoma/Data/", type, "/imputed.", type, ".data.Rdata"), compress=TRUE)
  }
  load(paste0("Z:/Project Melanoom/PaperMelanoma/Data/", type, "/imputed.", type, ".data.Rdata"))
  save(list=c(paste0("dd.", type), paste0(type, ".data.to.be.imputed"), "m", paste0("imputed.", type, ".data")),
       file=paste0("Z:/Project Melanoom/PaperMelanoma/Data/", type, "/", type, ".data.Rdata"), compress=TRUE)
}
```

Perform multiple imputation
```{r, eval=TRUE}
# erase memory
m <- 5
new.imputation <- TRUE
# Impute: Ulceration, Loc_CAT, Histology, Breslow, Tot_SNs_neg, Tot_SNs_pos, Rdamcrit, Dewar, Mitosis, logRec.time
impute.missing.values(type="training", m=m, new.imputation=new.imputation)
# Impute: Ulceration, Histology, Rdamcrit, Dewar, logRec.time
impute.missing.values(type="validation", m=m, new.imputation=new.imputation)
# Impute pooled data
# impute.missing.values(type="pooled", m=m, new.imputation=new.imputation)

# training data gives warning messages for Mitosis
# validation data gives multicolinearity of logRectime and recurrence
# print(imputed.data$loggedEvents)
```
