---
title: "Fit models and plots"
author: "Carolien C.H.M. Maas"
date: "January 2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load packages, functions, and data 
```{r, eval=TRUE, echo=TRUE, message=FALSE, warning=FALSE}
# erase memory
rm(list = ls(all.names = TRUE))

# for reproducibility
set.seed(100)

# load libraries
library(mice)
library(dplyr)
library(rms)
```

# Full model
```{r, eval=TRUE}
load("Z:/Project Melanoom/PaperMelanoma/Data/validation/validation.data.RData")

# set datadist
options(datadist="dd.validation")

# define the outcome based on last imputed data set
last.imputed.data.set <- mice::complete(imputed.validation.data, m)
S.Rec.validation <- survival::Surv(exp(last.imputed.data.set$logRec.time), last.imputed.data.set$Recurrence=="recurred")
S.Rec.5.validation <- S.Rec.validation
S.Rec.5.validation[S.Rec.validation[,1]>5, 1] <- 5 # set time to 5
S.Rec.5.validation[S.Rec.validation[,1]>5, 2] <- 0 # set censoring

# fit model
form.full.Rec.5.Mitosis.log <- S.Rec.5.validation ~
  SNstatus +
  Sex +
  Age.SN +
  Ulceration +
  Loc_CAT +
  Histology +
  log(Breslow) +
  multiple.fields +
  log(Mitosis+1) +
  Tot_SNs_neg +
  Tot_SNs_pos +
  log(Rdamcrit) +
  Dewar +
  SNstatus:Sex +
  SNstatus:Age.SN +
  SNstatus:Ulceration +
  SNstatus:Loc_CAT +
  SNstatus:Histology +
  SNstatus:log(Breslow) +
  SNstatus:multiple.fields +
  SNstatus:log(Mitosis+1)
f.mi.full.Rec.5.Mitosis.log <- Hmisc::fit.mult.impute(form.full.Rec.5.Mitosis.log, cph, 
                                          xtrans=imputed.validation.data,
                                          data=validation.data.to.be.imputed,
                                          n.impute=m, pr=FALSE, fit.reps=TRUE, 
                                          fitargs=list(y=TRUE, x=TRUE, 
                                                       se.fit=TRUE))
f.mi.full.Rec.5.Mitosis.log
stats::anova(f.mi.full.Rec.5.Mitosis.log)
plot(Predict(f.mi.full.Rec.5.Mitosis.log))

C.Mitosis.log.full <- c()
for (i in 1:m){
  C.Mitosis.log.full <- c(C.Mitosis.log.full, Hmisc::rcorr.cens(-predict(f.mi.full.Rec.5.Mitosis.log,
                                                       newdata=mice::complete(imputed.validation.data,i), type="lp"), 
                                                       S.Rec.5.validation)["C Index"])
}
mean(C.Mitosis.log.full)
``` 

# Final model after backward selection
```{r, eval=TRUE}
form.BS.Rec.5.Mitosis.log <- S.Rec.5.validation ~
  SNstatus +
  Sex +
  Age.SN +
  Ulceration +
  Loc_CAT +
  # Histology +
  log(Breslow) +
  # multiple.fields +
  log(Mitosis+1) +
  # Tot_SNs_neg +
  # Tot_SNs_pos +
  log(Rdamcrit) 
  # Dewar +
  # SNstatus:Sex +
  # SNstatus:Age.SN +
  # SNstatus:Ulceration +
  # SNstatus:Loc_CAT +
  # SNstatus:Histology +
  # SNstatus:log(Breslow) +
  # SNstatus:multiple.fields +
  # SNstatus:log(Mitosis+1)
f.mi.BS.Rec.5.Mitosis.log <- Hmisc::fit.mult.impute(form.BS.Rec.5.Mitosis.log, cph, 
                                          xtrans=imputed.validation.data,
                                          data=validation.data.to.be.imputed,
                                          n.impute=m, pr=FALSE, fit.reps=TRUE, 
                                          fitargs=list(y=TRUE, x=TRUE, 
                                                       se.fit=TRUE))
f.mi.BS.Rec.5.Mitosis.log
stats::anova(f.mi.BS.Rec.5.Mitosis.log)
plot(Predict(f.mi.BS.Rec.5.Mitosis.log))

C.Mitosis.log <- c()
for (i in 1:m){
  C.Mitosis.log <- c(C.Mitosis.log, Hmisc::rcorr.cens(-predict(f.mi.BS.Rec.5.Mitosis.log,
                                                       newdata=mice::complete(imputed.validation.data,i), type="lp"), 
                                                       S.Rec.5.validation)["C Index"])
}
mean(C.Mitosis.log)
``` 

```{r,eval=TRUE}
results.BS <- summary(f.mi.BS.Rec.5.Mitosis.log, SNstatus="Negative", Loc_CAT="arm")
table.BS <- rbind(exp(results.BS[c("SNstatus - Positive:Negative",
                                 "Mitosis", 
                                 "Age.SN",
                                 "Sex - female:male",
                                 "Ulceration - Yes:No",
                                 "Loc_CAT - leg:arm",
                                 "Loc_CAT - trunk:arm",
                                 "Loc_CAT - head & neck:arm",
                                 "Breslow",
                                 "Rdamcrit"), c("Effect", "Lower 0.95", "Upper 0.95")]))
BS.table <- cbind(sprintf("%.3f", table.BS[, 1]),
                      paste0("[", sprintf("%.3f", table.BS[, 2]), "; ", 
                             sprintf("%.3f", table.BS[, 3]), "]"))

# add reference rows
BS.table <- rbind(rep(NA, 2),             # SN status title
                  c("(ref)", NA),         # Negative SN status
                  BS.table[1:5,],         # Positive SN status, Mitosis, Age, Sex, Ulceration
                  rep(NA, 2),             # Location title
                  c("(ref)", NA),         # Upper limb ref
                  BS.table[6:10,])        # Lower limb, tunk, head&neck, Breslow, tumour burden

# add Chi-square statistics
anova.out <- anova(f.mi.BS.Rec.5.Mitosis.log)[, "Chi-Square"]
anova.main <- c(anova.out[c("SNstatus")], # SN status
                NA,               # negative SN
                NA,               # positive SN
                anova.out[c("Mitosis",
                            "Age.SN",     # Age
                            "Sex",
                            "Ulceration", # Ulceration
                            "Loc_CAT")],  # Location
                NA,               # upper limb
                NA,               # lower limb
                NA,               # trunk
                NA,               # head & neck
                anova.out[c("Breslow")], # Breslow
                anova.out[c("Rdamcrit")])
BS.table <- cbind(BS.table, sprintf("%.0f", anova.main))

colnames(BS.table) <- c("HR", "CI", "Imp.")
rownames(BS.table) <- c("SN status",
                         "Negative SN status",
                         "Positive SN status", 
                         "Mitosis (2 vs 7)",
                         "Age (46 vs. 68)", 
                         "Females",
                         "Ulceration",
                         "Location", 
                         "Upper limb", 
                         "Lower limb", 
                         "Trunk", 
                         "Head and neck",
                         "Breslow (1.3 vs 3.2)",
                         "SN tumour burden (0.01 vs. 23.0)")
BS.table[BS.table=="NA"] <- NA
BS.table[is.na(BS.table)] <- ""
BS.table
openxlsx::write.xlsx(as.data.frame(BS.table),
            rowNames=TRUE,
            file="Z:/Project Melanoom/PaperMelanoma/Results/Review/Final.Model.Australian.xlsx")
```
# Final model without Mitosis
```{r, eval=TRUE}
form.BS.Rec.5.without.Mitosis <- S.Rec.5.validation ~
  SNstatus +
  Sex + 
  Age.SN +
  Ulceration +
  Loc_CAT +
  log(Breslow) +
  log(Rdamcrit)
f.mi.BS.Rec.5.without.Mitosis <- Hmisc::fit.mult.impute(form.BS.Rec.5.without.Mitosis, cph, 
                                          xtrans=imputed.validation.data,
                                          data=validation.data.to.be.imputed,
                                          n.impute=m, pr=FALSE, fit.reps=TRUE, 
                                          fitargs=list(y=TRUE, x=TRUE, 
                                                       se.fit=TRUE))

C.without.Mitosis <- c()
for (i in 1:m){
  C.without.Mitosis <- c(C.without.Mitosis, Hmisc::rcorr.cens(-predict(f.mi.BS.Rec.5.without.Mitosis,
                                                       newdata=mice::complete(imputed.validation.data,i), type="lp"), 
                                                       S.Rec.5.validation)["C Index"])
}
mean(C.without.Mitosis)
``` 
# Test model with or without Mitosis
```{r, eval=TRUE}
AIC(f.mi.BS.Rec.5.Mitosis.log)
AIC(f.mi.BS.Rec.5.without.Mitosis)
LR.test.log <- lrtest(f.mi.BS.Rec.5.Mitosis.log, f.mi.BS.Rec.5.without.Mitosis)
LR.test.log
```

# Calculate optimism using bootstrap using full model and doing backward selection for each bootstrap
```{r, eval=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
set.seed(100)
slope<-NULL
cindex.orig<-NULL
opt<-NULL
cindex.B<-NULL
for (i in 1:m){
  v<-validate(f.mi.full.Rec.5.Mitosis.log$fits[[i]],method="boot",bw=TRUE,rule="p",sls=0.05,B=100,pr=FALSE,type="individual")
  slope<-c(slope,v["Slope","test"]) # slope of test
  cindex.orig<-c(cindex.orig,(v["Dxy","index.orig"]+1)/2) # original C-index
  opt<-c(opt,v["Dxy","optimism"]/2) # optimism C-index
  cindex.B<-c(cindex.B,(v["Dxy","index.corrected"]+1)/2) # index corrected C-index
}
mean(cindex.orig)
optimism <- mean(opt)
optimism
mean(cindex.B)
mean(cindex.orig)-optimism
```
```{r, eval=TRUE}
load("Z:/Project Melanoom/PaperMelanoma/Data/training/training.data.RData")
m <- 5
horizon <- 5
p.Rec.5.Europe <- matrix(NA, nrow(training.data.to.be.imputed), m)
p.Rec.5.Australia <- matrix(NA, nrow(validation.data.to.be.imputed), m)
for (i in 1:m){
  f.Rec.basehaz.i <- survival::basehaz(cph(form.BS.Rec.5.Mitosis.log, 
                                               data=mice::complete(imputed.validation.data, i), 
                                               se.fit=TRUE, x=TRUE, y=TRUE))
  h0.Rec.i <- f.Rec.basehaz.i$hazard[f.Rec.basehaz.i$time==max(f.Rec.basehaz.i$time[f.Rec.basehaz.i$time<=horizon])]
  
  lp.AUS.i <- predict(f.mi.BS.Rec.5.Mitosis.log,
                      newdata=mice::complete(imputed.validation.data, i),
                      type="lp")
  p.Rec.5.Australia[, i] <- 1-exp(-h0.Rec.i*exp(lp.AUS.i))
  
  imputed.training.data.i <- mice::complete(imputed.training.data, i)
  imputed.training.data.i$Mitosis <- as.numeric(imputed.training.data.i$Mitosis=="Yes")

  lp.EU.i <- predict(f.mi.BS.Rec.5.Mitosis.log,
                      newdata=imputed.training.data.i,
                      type="lp")
  p.Rec.5.Europe[, i] <- 1-exp(-h0.Rec.i*exp(lp.EU.i))
}
PredictionTools::val.surv.mi(p.Rec.5.Australia, S.Rec.5.validation,
                             g=5,main="Performance of Australian model for Australian patients", time=NULL,lim=c(0,1),dist=TRUE)
PredictionTools::val.surv.mi(p.Rec.5.Europe, S.Rec.5.training,
                             g=5,main="Performance of Australian model for European patients", time=NULL,lim=c(0,1),dist=TRUE)
``` 
